In [2]:
import numpy as np

# Adding,removing and sorting elements

In [2]:
array=np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [16]:
#np.insert-The insert function helps in adding an element to a specific index in an array
array1=np.insert(array,3,[6,7])
array1

array([1, 2, 3, 6, 7, 4, 5])

In [13]:
#The append function is used to add elements at the end of an array
array2=np.append(array,[6,7,8])
array2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
#np.delete-This function helps to delete an element by inputting the index
array3=np.delete(array,1)
array3

array([1, 3, 4, 5])

In [22]:
integers=np.random.randint(0,20,20)
integers

array([16, 13,  2,  9, 14, 14,  4, 17,  0, 16,  5,  9,  9, 10,  0, 13,  7,
        4, 16,  3])

In [23]:
#Sorting one dimensional array 
print(np.sort(integers))

[ 0  0  2  3  4  4  5  7  9  9  9 10 13 13 14 14 16 16 16 17]


In [29]:
integers1=np.array([[5,4,3,2,1],[6,7,5,4,3]])
integers1

array([[5, 4, 3, 2, 1],
       [6, 7, 5, 4, 3]])

In [28]:
#Sorting a 2 dimensional array
print(np.sort(integers1))

[[1 2 3 4 5]
 [0 6 7 8 9]]


In [30]:
#Sorting an array with string sorts them alphabetically
array=np.array(['red','green','yellow','blue','gold'])
array

array(['red', 'green', 'yellow', 'blue', 'gold'], dtype='<U6')

In [31]:
print(np.sort(array))

['blue' 'gold' 'green' 'red' 'yellow']


# Copies and Views

In [ ]:
#Copy is a new array and the view is different view of original array which is stored at a different loction
#View is a different view of the original array which gives a differently named reference to the same locatiion in the memory

In [54]:
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [55]:
students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

TypeError: 'numpy.ndarray' object is not callable

In [56]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [57]:
students_ids_number_cp=students_ids_number.copy()

In [58]:
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [59]:
print(students_ids_number_cp==students_ids_number)

[ True  True  True  True  True  True  True  True]


In [60]:
print ("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))

TypeError: 'numpy.ndarray' object is not callable

In [61]:
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [62]:
students_ids_number_v=students_ids_number.view()

In [63]:
students_ids_number_v[0]=2000
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [64]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]


# Reshaping arrays

In [2]:
#np.reshapeThis function helps to reshape an n dimensional array to m dimensional array
array=np.arange(1,13)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
#Reshaping a 1d array to 2d
array2=np.reshape(array,(4,3))
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
#Reshaping a 1d array to 3d array
array3=np.reshape(array,(2,3,2))
array3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [13]:
array=np.array([[1,2],[8,9],[2,3],[0,8]])
array

array([[1, 2],
       [8, 9],
       [2, 3],
       [0, 8]])

In [18]:
#Converting an n dimensional array to 1d array
#This can be done by writing -1
array1=np.reshape(array,-1)
array1

array([1, 2, 8, 9, 2, 3, 0, 8])

In [19]:
#numpy.ndarray.flatten-This helps to flatten an array and makes a copy of it without making chages to the original array
#numpy.ravel- opposite of flatten, this will flatten the array and make change to the original array
#ravel is memory efficient
array2=array.flatten()
print(array2)
array3=array.ravel()
print(array3)

[1 2 8 9 2 3 0 8]
[1 2 8 9 2 3 0 8]


In [20]:
array2[0]=100
array3[0]=200
print(array)
print(array2)
print(array3)

[[200   2]
 [  8   9]
 [  2   3]
 [  0   8]]
[100   2   8   9   2   3   0   8]
[200   2   8   9   2   3   0   8]


# Indexing and slicing

In [33]:
arrayx=np.reshape(np.arange(12),(3,4))
arrayx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
#Indexing the second ow, second element
arrayx[1,1]

5

In [24]:
array1=np.reshape(np.arange(60),(3,4,5))
array1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [26]:
#We can use negative numbers for indexing if we want the last from the back
array1[2,-1,-1]

59

In [27]:
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#slicing 4 elements
array[2:6]

array([2, 3, 4, 5])

In [30]:
#slicing the first 5 elements
array[:5]

array([0, 1, 2, 3, 4])

In [31]:
#slicing the last 3 elements
array[-3:]

array([7, 8, 9])

In [32]:
#Slicing the alternate elements
array[::2]

array([0, 2, 4, 6, 8])

In [35]:
arrayx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
arrayx[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [37]:
arrayx[1,:]

array([4, 5, 6, 7])

In [38]:
arrayx[:,2]

array([ 2,  6, 10])

# Joining and splitting arrays

In [18]:
#We can merge and break arrays
#concatenate-merging two arrays
array4=np.arange(1,11)
array5=np.arange(11,21)
print(array4)
print(array5)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [19]:
array3=np.concatenate((array4,array5))
array3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
array=np.array([[1,2,3,4],[5,6,7,8]])
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
array1=np.array([[9,10,11,12],[13,14,15,16]])
array1

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
#Putting axis=1 will keep the dimension of the array same and increasing the axis decreases the dimension of the array
array2=np.concatenate((array,array1),axis=1)
array2

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [20]:
st_arr = np.stack((array4,array5))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [22]:
#hstack-used for horizontal stacking
#vstack-used for vertical stacking
array_h=np.hstack((array4,array5))
array_h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
array_v=np.vstack((array4,array5))
array_v

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [24]:
#splitting arrays
#drawback-the number of elements should be divisible by the no. of splits
array5=np.arange(1,13)
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
array_s=np.array_split(array5,4)
array_s

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [26]:
print(array_s[2])

[7 8 9]


In [30]:
array_s=np.array_split(array5,8)
array_s

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]