In [1]:
import numpy as np

# Arithmetic operations and functions

In [16]:
a=np.arange(0,11)
b=np.arange(11,22)
print("a", a)
print("b", b)

a [ 0  1  2  3  4  5  6  7  8  9 10]
b [11 12 13 14 15 16 17 18 19 20 21]


In [17]:
#Using basic oerations like add, subract, multiply, divide if there are same no of elements in the arrays
a+b

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [18]:
b-a

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [19]:
a*b

array([  0,  12,  26,  42,  60,  80, 102, 126, 152, 180, 210])

In [22]:
b/a

/var/folders/12/06cl1m6x4992t10_b5krgjhc0000gn/T/ipykernel_52319/997269450.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  b//a


array([ 0, 12,  6,  4,  3,  3,  2,  2,  2,  2,  2])

In [26]:
c=np.arange(2,13)
print("c",c)

c [ 2  3  4  5  6  7  8  9 10 11 12]


In [27]:
a**c

array([            0,             1,            16,           243,
                4096,         78125,       1679616,      40353607,
          1073741824,   31381059609, 1000000000000])

In [28]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
#Another way to use operator
np.add(a,b)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [30]:
np.subtract(b,a)

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [31]:
np.multiply(a,b)

array([  0,  12,  26,  42,  60,  80, 102, 126, 152, 180, 210])

In [32]:
np.divide(b,a)

/var/folders/12/06cl1m6x4992t10_b5krgjhc0000gn/T/ipykernel_52319/3421666983.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(b,a)


array([        inf, 12.        ,  6.5       ,  4.66666667,  3.75      ,
        3.2       ,  2.83333333,  2.57142857,  2.375     ,  2.22222222,
        2.1       ])

In [33]:
np.mod(b,a)

/var/folders/12/06cl1m6x4992t10_b5krgjhc0000gn/T/ipykernel_52319/2975056474.py:1: RuntimeWarning: divide by zero encountered in remainder
  np.mod(b,a)


array([0, 0, 1, 2, 3, 1, 5, 4, 3, 2, 1])

In [34]:
np.power(a,c)

array([            0,             1,            16,           243,
                4096,         78125,       1679616,      40353607,
          1073741824,   31381059609, 1000000000000])

In [35]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

# Broadcasting

In [ ]:
#It helps to perform arithmetic operation with different array shapes
#It works when axes are one one by one basis, they have either same length or length of one


In [2]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [5]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [6]:
c=np.arange(1,3)
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [7]:
#broadcasing in action on a 3d array

In [8]:
d=np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [10]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

# Aggregate functions

In [11]:
#Statistics such as average, standard deviation,etc

In [12]:
a=np.arange(10,110,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
b=np.arange(10,100,10).reshape(3,3)
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
c=np.arange(10,110,10).reshape(2,5)
c

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [17]:
#Using the sum function to get the sum of elements in an array
a.sum()

550

In [18]:
b.sum()

450

In [19]:
c.sum()

550

In [20]:
#sum of each column
b.sum(axis=0)

array([120, 150, 180])

In [21]:
#sum of each row
b.sum(axis=1)

array([ 60, 150, 240])

In [23]:
#prod function- finds the product of an array
b.prod(axis=0)

array([ 28000,  80000, 162000])

In [24]:
#avg function- gives the average of an array
np.average(a)

55.0

In [25]:
np.average(b)

50.0

In [26]:
np.average(c)

55.0

In [27]:
#min and max-Finding the min and max of an array
np.min(a)

10

In [28]:
np.max(a)

100

In [29]:
#mean and standard deviation- finding the mean and standard deviation of first array
np.mean(a)

55.0

In [30]:
np.std(a)

28.722813232690143

# How to get unique items and count

In [33]:
# finding unique values and rows and coulmns in 1d and 2 d arrays and finging their frequency
a=np.array([1,2,2,3,3,4,5,6,7,8,4,2,0,10,4,2,1])
a

array([ 1,  2,  2,  3,  3,  4,  5,  6,  7,  8,  4,  2,  0, 10,  4,  2,  1])

In [35]:
#Getting unique elements from an array
np.unique(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [36]:
b=np.array([[1, 1, 2,1] ,[ 3, 1, 2,1] , [1, 1, 2, 1], [ 7, 1, 1, 1]])
b

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [38]:
np.unique(b)

array([1, 2, 3, 7])

In [39]:
#Outputting the unique columns
#column 3 is duplicate of column 1
np.unique(b,axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [40]:
#Outputting the unique rows
#row 4 is duplicate of row 1
np.unique(b,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [42]:
#The first array which we get is the unique elements
#The second array which we get is the index of the unique elements
np.unique(a,return_index=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([12,  0,  1,  3,  5,  6,  7,  8,  9, 13]))

In [43]:
#Finding the frequency count of the unique elements
np.unique(b,return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1]))

# Transpose like operations

In [44]:
#Finding transpose of an array similar to a matrix
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
b=np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
#Transposing an array with axis function
np.transpose(b,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [50]:
#np.moveaxis-moves axes of an array to new positions
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
c.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [52]:
c.swapaxes(0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

# Reversing an array

In [53]:
#Reversing an array by using slicing
a=np.array([10,1,9,2,8,3,7,4,6,5])
a

array([10,  1,  9,  2,  8,  3,  7,  4,  6,  5])

In [56]:
a[::-1]

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [59]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
#using a flip function to reverse an array
np.flip(b)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [61]:
#If we weant to reverse elements row by row, then we will use the axes
np.flip(b,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [62]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [63]:
#Reversing a 3d array over different axes
np.flip(c,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [64]:
np.flip(c,2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])