# Numpy Array types and creating Numpy Arrays

There are various advantages of Numpy arrays as compared to lists.
The arrays are 100x faster and take less memory as compared to lists.
The arrays save elements of same data type while lists can save elements with different data type.

# Array types and conversions between types

In [10]:
#Importing numpy
import numpy as np

In [140]:
#Creating an array with five integers
integers=np.array([10,20,30,40,50])
integers

array([10, 20, 30, 40, 50])

In [141]:
#Checking the first element in the array integers(in computers, numbers start from 0)
integers[0]

10

In [18]:
#Changing the value of the first element in array to 20 and then printing the array
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [19]:
#changing value of one element to float but the output is int because array can save elements with same data types 
integers[0]=21.5
integers

array([21, 20, 30, 40, 50])

In [21]:
#Checking the data type of an array
integers.dtype

dtype('int64')

In [22]:
#changing the data type of integers array from int 64 to int 8
smallintegers=np.array(integers, dtype=np.int8)
smallintegers

array([21, 20, 30, 40, 50], dtype=int8)

In [23]:
#nbytes function tells us the (memory) bytes consumed by an array
#we will see that smallintegers take 8 times less memory
integers.nbytes

40

In [24]:
smallintegers.nbytes

5

In [26]:
#We have to be careful with dtype function to prevent an overflow
overflow=np.array([127,128,129],dtype=np.int8)
overflow

array([ 127, -128, -127], dtype=int8)

In [27]:
#Numpy can also determine the data type of float
floats=np.array([1.2,2.3,3.4,4.5,5.6])
print(floats)

[1.2 2.3 3.4 4.5 5.6]


In [28]:
floats.dtype

dtype('float64')

# Multidimensional arrays

In [31]:
#We have seen the one dimensionals array previously
#Now, there are mulidimensional array like a matrix and tensor(3d array)
#creating a matrix
nums=np.array([[1,2,3],[4,5,6],[7,8,9]])
nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
#Checking the first element in the first array
nums[0,0]

1

In [34]:
#Checking the first element in the second row
nums[1,0]

4

In [35]:
#Checking the dimension of the array
nums.ndim

2

In [42]:
#creating a tensor(3d array)
ten=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ten

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
ten.ndim

3

In [44]:
#Checking an element in 3d array
ten[1,0,1]

8

In [ ]:
#In this way 4,5, and other multi dimensional arrays can be built without any problem

# Creating arrays from python objects

In [46]:
#We can create an array from a list or tuples
list=[1,2,3,4,5,6,7,8,9,0]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [47]:
array=np.array(list)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [52]:
#Creating array from a list which has both int and float
list=[1,2,3,-1,.23,50,129999000.12,4.56]
list

[1, 2, 3, -1, 0.23, 50, 129999000.12, 4.56]

In [53]:
array=np.array(list)
array

array([ 1.00000e+00,  2.00000e+00,  3.00000e+00, -1.00000e+00,
        2.30000e-01,  5.00000e+01,  1.29999e+08,  4.56000e+00])

In [54]:
#The data type of array is float64 which has int and float in a list
array.dtype

dtype('float64')

In [59]:
#Creating an array from a list which has both int and strings
list=[1,2,-50,-99,'Hello bete']
list

[1, 2, -50, -99, 'Hello bete']

In [60]:
#In this case, all the elements in the list will turn into strings
array=np.array(list)
array

array(['1', '2', '-50', '-99', 'Hello bete'], dtype='<U21')

In [61]:
array.dtype

dtype('<U21')

In [62]:
#creating an array from a tuple
tuple=(1,2,3,4,5,6,7,8,9,0)
tuple

(1, 2, 3, 4, 5, 6, 7, 8, 9, 0)

In [64]:
array=np.array(tuple)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [65]:
array.dtype

dtype('int64')

In [67]:
#creating a three dimensional array from a list
multi_dim_list=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
multi_dim_list

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [70]:
array=np.array(multi_dim_list)
array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Intrinsic Numpy array creation

In [71]:
#These funcions help to quickly generate arrays with many elements
#np.arange-this is simlar to python range function and adds elements to
#an array and we can choose the difference between two numbers
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
#setting range between 100 and 130
array=np.arange(100,130)
array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [93]:
#setting the first and last point, and the difference between the elements
array=np.arange(50,101,2)
array

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [143]:
#np.linspace-This helps to create an array where we can choose the number of elements between the given set
array=np.linspace(100,110)
array

array([100.        , 100.20408163, 100.40816327, 100.6122449 ,
       100.81632653, 101.02040816, 101.2244898 , 101.42857143,
       101.63265306, 101.83673469, 102.04081633, 102.24489796,
       102.44897959, 102.65306122, 102.85714286, 103.06122449,
       103.26530612, 103.46938776, 103.67346939, 103.87755102,
       104.08163265, 104.28571429, 104.48979592, 104.69387755,
       104.89795918, 105.10204082, 105.30612245, 105.51020408,
       105.71428571, 105.91836735, 106.12244898, 106.32653061,
       106.53061224, 106.73469388, 106.93877551, 107.14285714,
       107.34693878, 107.55102041, 107.75510204, 107.95918367,
       108.16326531, 108.36734694, 108.57142857, 108.7755102 ,
       108.97959184, 109.18367347, 109.3877551 , 109.59183673,
       109.79591837, 110.        ])

In [88]:
#setting the firt,last point and the number of elements in the array
array=np.linspace(10,20,21)
array

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [107]:
#np.random.rand-This will create an array with random numbers and creates multidimensional array if given such an input
#The first number is the no of elements, second argument is the number of columns
array=np.random.rand(10)
array

array([0.95404161, 0.21108081, 0.46590549, 0.95453075, 0.04438144,
       0.9659248 , 0.23179928, 0.48990013, 0.17193084, 0.464103  ])

In [109]:
array=np.random.rand(5,3)
array

array([[0.42311659, 0.49069065, 0.0398431 ],
       [0.73463533, 0.29994795, 0.88639399],
       [0.40598044, 0.06571661, 0.43224181],
       [0.36302213, 0.42103722, 0.85086238],
       [0.15058523, 0.62609988, 0.60167694]])

In [113]:
#random.randint-this creates a random int array
#The first number is min, second is max, third is the number of elements in the array
array=np.random.randint(10,20)
array

16

In [115]:
array=np.random.randint(10,20,10)
array

array([10, 17, 18, 17, 13, 14, 15, 11, 10, 14])

# Creating arrays filled with constant values

In [116]:
#np.zero-creating an array with zero value
array=np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [118]:
#We have to create a tuple where first number is no of rows, second no is no of columns
array=np.zeros((5,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [120]:
#np.ones-creating an array with pure ones
array=np.ones(5)
array

array([1., 1., 1., 1., 1.])

In [122]:
#We have to create a tuple where first number is no of rows, second no is no of columns
array=np.ones((5,4))
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [123]:
array=np.ones((5,4),dtype=int)
array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [126]:
#np.ndarray.fill-used to create one dimensional array
#np.full-used to create both one and two dimensional arrays
array=np.empty(10,dtype=int)
array.fill(12)
array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [127]:
#The first number is the no of times you need that number, second number is the number which will get in the array
array=np.full(5,10)
array

array([10, 10, 10, 10, 10])

In [128]:
#creating a 2d array with 4 rows, 5 columns with the number 8
array=np.full((4,5),8)
array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

# Finding shape and size of an array

In [129]:
array1=np.arange(20)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
array2=np.linspace((1,2),(10,20),10)
array2

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [131]:
array3=np.full((2,2,2),10)
array3

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [132]:
#The shape tells us the no of elements in the 1st dim, then 2nd dim,...
np.shape(array1)

(20,)

In [133]:
np.shape(array2)

(10, 2)

In [134]:
np.shape(array3)

(2, 2, 2)

In [138]:
#The size function helps us determine the no of elements in an array
np.size(array1)

20

In [139]:
np.size(array2)

20

In [137]:
np.size(array3)

8